statechain_entity = "http://127.0.0.1:8000"
#statechain_entity = "http://j23wevaeducxuy3zahd6bpn4x76cymwz2j3bdixv7ow4awjrg5p6jaid.onion"
#electrum_server = "tcp://127.0.0.1:50001"
electrum_server = "tcp://signet-electrumx.wakiyamap.dev:50001"
electrum_type = "electrs"
network = "signet"
fee_rate_tolerance = 5
database_file="wallet.db"
confirmation_target = 2
#tor_proxy = "socks5h://localhost:9050"