./modify_sh/modify_kt_file.sh
./modify_sh/modify_token.sh
./modify_sh/modify_deposit_msg1.sh
./modify_sh/modify_deposit_msg_response.sh
./modify_sh/modify_sign_first_request_payload.sh
./modify_sh/modify_sign_first_response_payload.sh
./modify_sh/modify_partial_signature_request_payload.sh
./modify_sh/modify_partial_signature_response_payload.sh
./modify_sh/modify_transfer_sender_request_payload.sh
./modify_sh/modify_transfer_update_msg_request_payload.sh
./modify_sh/modify_get_msg_addr_response_payload.sh
./modify_sh/modify_key_update_response_payload.sh
./modify_sh/modify_statechain_info.sh
./modify_sh/modify_statechainInfo_response_payload.sh
./modify_sh/modify_transfer_receiver_request_payload.sh
./modify_sh/modify_transfer_receiver_post_response_payload.sh
./modify_sh/modify_transfer_receiver_get_response_payload.sh
./modify_sh/modify_transfer_receiver_error.sh
./modify_sh/modify_transfer_unlock_request_payload.sh
