name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        -
          name: Checkout
          uses: actions/checkout@v4
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: commerceblockx
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - 
          name: Get last commit hash
          id: get_commit_hash
          run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        -
          name: Build and push for mercury-server
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./server/Dockerfile
            push: true
            tags: commerceblockx/mercury-server:${{ env.COMMIT_HASH }}
        -
          name: Build and push for token-server
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./token-server/Dockerfile
            push: true
            tags: commerceblockx/token-server:${{ env.COMMIT_HASH }}
        -
          name: Build and push for mercury-explorer
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./explorer/Dockerfile
            push: true
            tags: commerceblockx/mercury-explorer:${{ env.COMMIT_HASH }}
        -
          name: Build and push for keylist-cronjob
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./keylistCron/Dockerfile
            push: true
            tags: commerceblockx/keylist-cronjob:${{ env.COMMIT_HASH }}
